### ISSUE TITLE
Additions and updates to documentation

### ISSUE THREAD

**Issue by ossmith** [harpak-lab/sad_variance#16]
A few of the details in the documentation and arguments could benefit from clarification and consistency.
- The naming schema is different between the two QuickStart commands (`pgsus_height_example` vs `pegasus_height_decomposition`), so they don't work together smoothly
- `--chrom-pos` label for decomposition isn't defined (default behavior is unclear and causes unclear error). Seems like it should default to 'SNP' instead of 'chr.pos' since this is the output from/consistent with munge.
- `--bfile` documentation doesn't clarify that this should just be the file stem (says 'bed file') and doesn't note what the default is
- I think just including the name of the `--anc-data` file in the documentation would be good since it's non-obvious

Details around PRSice in munge:
- Add PRSice as a dependency (or mention the conditions where it would be required) plus relevant instructions/pointer to install
- Has this been tested with MacOS? `PRSice_linux` command is hardcoded as of now, so if there's no intent to add other OSs, I think it should just be noted in the documentation that this is only for Linux systems. (It's also a bit confusing since their instructions expect the command "PRSice")

**Comment by smithsap** [comment]
Thank you!

A few updates: 

- The naming schema is different between the two QuickStart commands (pgsus_height_example vs pegasus_height_decomposition), so they don't work together smoothly. *Updated the naming to be the same throughout. 

- --chrom-pos label for decomposition isn't defined (default behavior is unclear and causes unclear error). Seems like it should default to 'SNP' instead of 'chr.pos' since this is the output from/consistent with munge. *For consistency this will probably remain unchanged. rsIDs are usually referred to as SNP so there needs to be a way to delineate between those and physical encoding. 

- --bfile documentation doesn't clarify that this should just be the file stem (says 'bed file') and doesn't note what the default is *Updated so that the munging script no longer attempts to clump, making this flag obsolete

- I think just including the name of the --anc-data file in the documentation would be good since it's non-obvious *Updated to give the explicit path that will be used.
